from django.urls import path
from . import views

urlpatterns = [
    # SEO endpoints — must be at root so crawlers find them at the conventional
    # paths (/robots.txt, /sitemap.xml). Both are cached for an hour.
    path('robots.txt', views.robots_txt, name='robots_txt'),
    path('sitemap.xml', views.sitemap_xml, name='sitemap_xml'),
    # Vendor library passthrough — sidesteps whitenoise's quoted-charset
    # Content-Type bug that breaks Edge under nosniff. See views.vendor_lib.
    path('lib/<str:name>', views.vendor_lib, name='vendor_lib'),
    path('', views.index, name='index'),
    # Public referral landing — /r/<CODE>/ stamps the session and bounces
    # to /signup/ so first-time visitors get attributed to the referrer.
    path('r/<str:code>/', views.referral_redirect_view, name='referral_redirect'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    # Google OAuth (Sign in / Sign up with Google)
    path('auth/google/start/',    views.google_oauth_start,    name='google_oauth_start'),
    path('auth/google/callback/', views.google_oauth_callback, name='google_oauth_callback'),
    path('onboarding/', views.onboarding_view, name='onboarding'),
    path('paywall/', views.paywall_view, name='paywall'),
    path('logout/', views.logout_view, name='logout'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('reset-password/<str:token>/', views.reset_password, name='reset_password'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/data/', views.dashboard_data_view, name='dashboard_data'),
    path('permits/', views.permits, name='permits'),
    path('permits/data/', views.permits_data_view, name='permits_data'),
    path('notifications/', views.notifications, name='notifications'),
    path('settings/', views.settings_view, name='settings'),
    path('profile/', views.profile, name='profile'),
    path('pricing/', views.pricing, name='pricing'),
    path('developers/', views.api_docs, name='api_docs'),
    path('blog/', views.blog, name='blog'),
    path('blog/<slug:slug>/', views.blog_post, name='blog_post'),
    path('careers/', views.careers, name='careers'),
    path('press/', views.press, name='press'),
    path('contact/', views.contact, name='contact'),
    path('support/', views.support, name='support'),
    path('support/new/', views.support_new_ticket, name='support_new_ticket'),
    path('support/ticket/<int:ticket_id>/', views.support_ticket_detail, name='support_ticket_detail'),
    path('support/api/tickets/', views.support_widget_tickets, name='support_widget_tickets'),
    path('support/api/tickets/<int:ticket_id>/', views.support_widget_ticket, name='support_widget_ticket'),
    path('support/api/tickets/<int:ticket_id>/reply/', views.support_widget_reply, name='support_widget_reply'),
    path('support/api/tickets/<int:ticket_id>/delete/', views.support_widget_delete, name='support_widget_delete'),
    path('support/api/notifications/read/', views.support_widget_mark_read, name='support_widget_mark_read'),
    path('admin-panel/support/', views.admin_support_view, name='admin_support'),
    path('admin-panel/support/<int:ticket_id>/', views.admin_support_ticket_view, name='admin_support_ticket'),
    path('admin-panel/api/support/notifications/', views.admin_support_notifications, name='admin_support_notifications'),
    path('admin-panel/api/support/notifications/read/', views.admin_support_mark_read, name='admin_support_mark_read'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('admin-panel/',          views.admin_dashboard,    name='admin_dashboard'),
    path('admin-panel/scrapers/',                          views.admin_scrapers_view,        name='admin_scrapers'),
    path('admin-panel/scrapers/data.json',                 views.admin_scrapers_data,        name='admin_scrapers_data'),
    path('admin-panel/scrapers/export.csv',                views.admin_scrapers_export_csv,  name='admin_scrapers_export_csv'),
    path('admin-panel/scrapers/new/',                      views.admin_scraper_new_view,     name='admin_scraper_new'),
    path('admin-panel/scrapers/<int:sid>/',                views.admin_scraper_detail_view,  name='admin_scraper_detail'),
    path('admin-panel/scrapers/<int:sid>/permits.json',    views.admin_scraper_permits_data, name='admin_scraper_permits_data'),
    path('admin-panel/scrapers/<int:sid>/permits/bulk-delete/', views.admin_scraper_permits_bulk_delete, name='admin_scraper_permits_bulk_delete'),
    path('admin-panel/scrapers/<int:sid>/permits/delete-all/', views.admin_scraper_permits_delete_all, name='admin_scraper_permits_delete_all'),
    path('admin-panel/scrapers/<int:sid>/run/',            views.admin_scraper_run_now,      name='admin_scraper_run_now'),
    path('admin-panel/scrapers/<int:sid>/backfill/',       views.admin_scraper_backfill,     name='admin_scraper_backfill'),
    path('admin-panel/scrapers/<int:sid>/toggle-enabled/', views.admin_scraper_toggle_enabled, name='admin_scraper_toggle_enabled'),
    path('admin-panel/scrapers/agent/settings/',           views.admin_scraper_agent_save_settings, name='admin_scraper_agent_save_settings'),
    path('admin-panel/scrapers/<int:sid>/delete/',         views.admin_scraper_delete,       name='admin_scraper_delete'),
    path('admin-panel/scrapers/bulk-delete/',              views.admin_scrapers_bulk_delete, name='admin_scrapers_bulk_delete'),
    path('admin-panel/scrapers/<int:sid>/update/',         views.admin_scraper_update_meta,  name='admin_scraper_update_meta'),
    path('admin-panel/permits/<int:pid>/raw/',             views.admin_permit_raw_view,      name='admin_permit_raw'),
    path('admin-panel/permits/<int:pid>/edit/',            views.admin_permit_edit_view,     name='admin_permit_edit'),
    path('admin-panel/permits/',                           views.admin_all_permits_view,     name='admin_all_permits'),
    path('admin-panel/permits/data.json',                  views.admin_all_permits_data,     name='admin_all_permits_data'),
    path('admin-panel/permits/bulk-delete/',               views.admin_all_permits_bulk_delete, name='admin_all_permits_bulk_delete'),
    path('admin-panel/scrapers/runs/<int:rid>/status/',    views.admin_scraper_run_status,   name='admin_scraper_run_status'),
    path('admin-panel/scrapers/runs/<int:rid>/cancel/',    views.admin_scraper_run_cancel,   name='admin_scraper_run_cancel'),
    path('admin-panel/scrapers/runs/<int:rid>/force-stop/',views.admin_scraper_run_force_stop, name='admin_scraper_run_force_stop'),
    path('admin-panel/scrapers/runs/<int:rid>/kill/',     views.admin_scraper_run_kill_process, name='admin_scraper_run_kill_process'),
    path('admin-panel/scrapers/run-all/',                        views.admin_run_all_scrapers,     name='admin_run_all_scrapers'),
    path('admin-panel/scrapers/run-selected/',                   views.admin_run_selected_scrapers, name='admin_run_selected_scrapers'),
    path('admin-panel/scrapers/save-default-pages/',             views.admin_scrapers_save_default_pages, name='admin_scrapers_save_default_pages'),
    path('admin-panel/scrapers/save-default-threads/',           views.admin_scrapers_save_default_threads, name='admin_scrapers_save_default_threads'),
    path('admin-panel/scrapers/stop-all/',                       views.admin_stop_all_scrapers,    name='admin_stop_all_scrapers'),
    path('admin-panel/scrapers/<int:sid>/stop-run/',             views.admin_stop_scraper_latest_run, name='admin_stop_scraper_latest_run'),
    path('admin-panel/scrapers/active-batch/',                   views.admin_active_batch,         name='admin_active_batch'),
    path('admin-panel/scrapers/cron/',                          views.admin_scraper_cron_view,    name='admin_scraper_cron'),
    path('admin-panel/scrapers/cron/save/',                     views.admin_scraper_cron_save,    name='admin_scraper_cron_save'),
    path('admin-panel/scrapers/cron/save-key/',                 views.admin_scraper_cron_save_key, name='admin_scraper_cron_save_key'),
    path('admin-panel/scrapers/cron/run-now/',                  views.admin_run_cron_now,         name='admin_run_cron_now'),
    path('admin-panel/scrapers/cron/batch/<int:batch_id>/',     views.admin_cron_batch_status,    name='admin_cron_batch_status'),
    path('admin-panel/scrapers/cron/heartbeat/',                views.admin_cron_heartbeat_status,name='admin_cron_heartbeat_status'),
    path('admin-panel/scrapers/accela-search/',                 views.admin_scraper_accela_search_view, name='admin_scraper_accela_search'),
    path('admin-panel/scrapers/accela-search/run/',             views.admin_scraper_accela_search_run,  name='admin_scraper_accela_search_run'),
    path('admin-panel/scrapers/accela-search/push/',            views.admin_scraper_accela_search_push, name='admin_scraper_accela_search_push'),
    path('admin-panel/scrapers/accela-search/settings/',        views.admin_scraper_accela_search_save_settings, name='admin_scraper_accela_search_save_settings'),
    path('admin-panel/scrapers/accela-search/finder-log/',                    views.admin_finder_request_log,  name='admin_finder_request_log'),
    path('admin-panel/scrapers/accela-search/finder-batch/start/',           views.admin_finder_batch_start,  name='admin_finder_batch_start'),
    path('admin-panel/scrapers/accela-search/finder-batch/<int:batch_id>/',  views.admin_finder_batch_status, name='admin_finder_batch_status'),
    path('admin-panel/scrapers/accela-search/finder-batch/stop/',            views.admin_finder_batch_stop,   name='admin_finder_batch_stop'),
    path('admin-panel/scrapers/accela-search/finder-batch/active/',          views.admin_finder_batch_active, name='admin_finder_batch_active'),
    path('admin-panel/scrapers/agent-plan/',                    views.admin_scraper_agent_plan_view,    name='admin_scraper_agent_plan'),
    path('admin-panel/scrapers/<int:sid>/runs/<int:rid>/log/',    views.admin_scraper_run_log_view,    name='admin_scraper_run_log'),
    path('admin-panel/scrapers/<int:sid>/runs/<int:rid>/delete/', views.admin_scraper_run_delete_view, name='admin_scraper_run_delete'),
    path('admin-panel/scraper-settings/',                  views.admin_scraper_settings_view,name='admin_scraper_settings'),
    path('admin-panel/scraper-stats/',                     views.admin_scraper_stats_view,   name='admin_scraper_stats'),
    path('admin-panel/scrapers/inference-stats/',          views.admin_inference_stats_view, name='admin_inference_stats'),
    path('admin-panel/scraper-logs/',                      views.admin_scraper_logs_index_view,        name='admin_scraper_logs'),
    path('admin-panel/scraper-logs/<int:sid>/',            views.admin_scraper_logs_detail_view,       name='admin_scraper_logs_detail'),
    path('admin-panel/scraper-logs/<int:sid>/bulk-delete/', views.admin_scraper_logs_bulk_delete_view, name='admin_scraper_logs_bulk_delete'),
    path('admin-panel/users/',    views.admin_users_view,    name='admin_users'),
    # htmx partial: just the <tr> rows for the Users table. Loaded
    # async by admin_users.html so the page chrome ships in <50 ms
    # and the table fills in a moment later.
    path('admin-panel/users/_rows/', views.admin_users_rows_view, name='admin_users_rows'),
    path('admin-panel/revenue/',  views.admin_revenue_view,  name='admin_revenue'),
    path('admin-panel/cities/',          views.admin_cities_view,          name='admin_cities'),
    path('admin-panel/cities-manager/',  views.admin_cities_manager_view,  name='admin_cities_manager'),
    # ── States manager ─────────────────────────────────────────
    # Per-state stats (moved off the scraper-stats page), banned-
    # states list for ingest, and per-state "delete permits" button.
    path('admin-panel/states/',                       views.admin_states_view,            name='admin_states'),
    path('admin-panel/states/data.json',              views.admin_states_data,            name='admin_states_data'),
    path('admin-panel/states/ban/',                   views.admin_states_ban,             name='admin_states_ban'),
    path('admin-panel/states/<str:code>/delete-permits/', views.admin_states_delete_permits, name='admin_states_delete_permits'),
    # ── DB Utilities (admin-only) ──────────────────────────────
    # One small page with two dangerous-but-occasionally-needed
    # buttons (wipe permits, backup DB). Backups land in ./backups/
    # and are auto-pruned to the 3 most recent so disk usage stays
    # bounded. See views.admin_db_utils_view for the full notes.
    path('admin-panel/db-utils/',                          views.admin_db_utils_view,             name='admin_db_utils'),
    path('admin-panel/db-utils/wipe-permits/',             views.admin_db_utils_wipe_permits,     name='admin_db_utils_wipe_permits'),
    path('admin-panel/db-utils/wipe-junk/',                views.admin_db_utils_wipe_junk,        name='admin_db_utils_wipe_junk'),
    path('admin-panel/db-utils/storage/save/',             views.admin_db_utils_storage_save,     name='admin_db_utils_storage_save'),
    path('admin-panel/db-utils/dropbox/exchange-code/',    views.admin_db_utils_dropbox_exchange, name='admin_db_utils_dropbox_exchange'),
    path('admin-panel/db-utils/backup/create/',            views.admin_db_utils_backup_create,    name='admin_db_utils_backup_create'),
    path('admin-panel/db-utils/backup/list.json',          views.admin_db_utils_backup_list,      name='admin_db_utils_backup_list'),
    path('admin-panel/db-utils/dropbox/diag/',             views.admin_db_utils_dropbox_diag,     name='admin_db_utils_dropbox_diag'),
    path('admin-panel/db-utils/backup/<str:filename>/download/', views.admin_db_utils_backup_download, name='admin_db_utils_backup_download'),
    path('admin-panel/db-utils/backup/<str:filename>/delete/',   views.admin_db_utils_backup_delete,   name='admin_db_utils_backup_delete'),
    path('admin-panel/banned/',         views.admin_banned_view,      name='admin_banned'),
    path('admin-panel/email-settings/', views.admin_email_settings,   name='admin_email_settings'),
    path('admin-panel/whop-settings/', views.admin_whop_settings,    name='admin_whop_settings'),
    path('admin-panel/whop-resync-user/', views.admin_whop_resync_user, name='admin_whop_resync_user'),
    path('admin-panel/google-settings/', views.admin_google_settings, name='admin_google_settings'),
    # ── Marketing (Analytics & Pixels, Testimonials, Recovery Emails) ──
    path('admin-panel/marketing/analytics/',       views.admin_analytics_view,       name='admin_analytics'),
    path('admin-panel/marketing/testimonials/',    views.admin_testimonials_view,    name='admin_testimonials'),
    path('admin-panel/marketing/recovery-emails/', views.admin_recovery_emails_view, name='admin_recovery_emails'),
    path('admin-panel/marketing/recovery-emails/preview/', views.admin_recovery_email_preview, name='admin_recovery_email_preview'),
    # ── Email campaigns (CSV + Resend bulk send) ────────────────
    path('admin-panel/marketing/campaigns/',                 views.admin_campaigns_list_view,        name='admin_campaigns_list'),
    path('admin-panel/marketing/campaigns/<int:cid>/',       views.admin_campaign_detail_view,       name='admin_campaign_detail'),
    path('admin-panel/marketing/campaigns/<int:cid>/recipients/', views.admin_campaign_recipients_data, name='admin_campaign_recipients_data'),
    path('admin-panel/marketing/campaigns/<int:cid>/preview/',    views.admin_campaign_preview,         name='admin_campaign_preview'),
    # ── Contractor email pool (source for campaigns) ────────────
    path('admin-panel/marketing/contractor-emails/',             views.admin_contractor_emails_view,   name='admin_contractor_emails'),
    path('admin-panel/marketing/contractor-emails/data/',        views.admin_contractor_emails_data,   name='admin_contractor_emails_data'),
    path('admin-panel/marketing/contractor-emails/pull/',        views.admin_contractor_emails_pull,   name='admin_contractor_emails_pull'),
    path('api/cron/campaigns/tick/',                         views.api_campaigns_tick_view,          name='api_campaigns_tick'),
    path('webhooks/resend/',                                 views.resend_webhook,                   name='resend_webhook'),
    path('u/<str:token>/',                                   views.campaign_unsubscribe_view,        name='campaign_unsubscribe'),
    path('admin-panel/marketing/pricing/',         views.admin_pricing_view,         name='admin_pricing'),
    # Public trade landing pages — /leads/<roofing|hvac|plumbing|electrical|solar>/
    path('leads/<slug:trade>/', views.trade_landing_view, name='trade_landing'),
    # Admin Blog editor
    path('admin-panel/blog/',                   views.admin_blog_view,           name='admin_blog'),
    path('admin-panel/blog/new/',               views.admin_blog_editor_view,    name='admin_blog_new'),
    path('admin-panel/blog/edit/<slug:slug>/',  views.admin_blog_editor_view,    name='admin_blog_edit'),
    path('admin-panel/blog/scrape/',            views.admin_blog_scrape,         name='admin_blog_scrape'),
    path('admin-panel/blog/rewrite/',           views.admin_blog_rewrite,        name='admin_blog_rewrite'),
    path('admin-panel/blog/publish/',           views.admin_blog_publish,        name='admin_blog_publish'),
    path('admin-panel/blog/delete/<slug:slug>/',views.admin_blog_delete,         name='admin_blog_delete'),
    path('admin-panel/blog-settings/',          views.admin_blog_settings_view,  name='admin_blog_settings'),
    path('admin-panel/delete/<int:user_id>/', views.admin_delete_user, name='admin_delete_user'),
    path('admin-panel/bulk-delete/',          views.admin_bulk_delete_users, name='admin_bulk_delete_users'),
    path('admin-panel/whop-mode/<int:user_id>/', views.admin_set_user_whop_mode, name='admin_set_user_whop_mode'),
    path('admin-panel/bulk-whop-mode/',          views.admin_bulk_set_whop_mode, name='admin_bulk_set_whop_mode'),
    path('admin-panel/email-code/<int:user_id>/', views.admin_set_user_email_code, name='admin_set_user_email_code'),
    path('admin-panel/bulk-whop-sync/',          views.admin_bulk_whop_sync,     name='admin_bulk_whop_sync'),
    path('admin-panel/ban/<int:user_id>/',    views.admin_ban_user,    name='admin_ban_user'),
    path('admin-panel/unban/',                views.admin_unban_email, name='admin_unban_email'),
    path('settings/alerts/',        views.save_alert_prefs,   name='save_alert_prefs'),
    path('settings/login-history/clear/', views.clear_login_history, name='clear_login_history'),
    path('settings/cities/add/',    views.add_city_view,    name='add_city'),
    path('settings/cities/remove/', views.remove_city_view, name='remove_city'),
    path('settings/billing-address/', views.save_billing_address, name='save_billing_address'),
    path('settings/security/change-password/', views.security_change_password, name='security_change_password'),
    path('settings/security/action/',          views.security_account_action,   name='security_account_action'),
    path('settings/security/revoke-session/',      views.revoke_session,      name='revoke_session'),
    path('settings/security/revoke-all-sessions/', views.revoke_all_sessions, name='revoke_all_sessions'),
    # True "sign out everywhere": revokes ALL sessions for this user
    # including the current one, so every device (including this tab)
    # has to re-authenticate. Differs from revoke-all-sessions which
    # keeps the current device alive. Used by the absolute-timeout
    # popup + the settings Active Sessions panel.
    path('settings/security/sign-out-everywhere/', views.sign_out_everywhere, name='sign_out_everywhere'),
    # Lightweight JSON poll used by the absolute-timeout popup in
    # base.html — tells the front-end exactly how many seconds remain
    # until the server-side cap fires, so the countdown stays in sync
    # with the server even if the browser clock drifts.
    path('api/session-status/',                    views.session_status,      name='session_status'),
    path('settings/security/totp-setup/',          views.totp_setup_qr,       name='totp_setup_qr'),
    path('settings/security/totp-verify/',         views.totp_verify_enable,  name='totp_verify_enable'),
    path('settings/security/totp-disable/',        views.totp_disable,        name='totp_disable'),
    path('login/2fa/',                             views.login_2fa,           name='login_2fa'),
    path('login/verify-code/',                     views.login_verify_code,        name='login_verify_code'),
    path('login/verify-code/resend/',              views.login_verify_code_resend, name='login_verify_code_resend'),
    path('billing/checkout/',          views.ls_checkout,           name='ls_checkout'),
    path('billing/embed/',             views.ls_embed_checkout,     name='ls_embed_checkout'),
    path('billing/success/',           views.ls_success,            name='ls_success'),
    path('billing/portal/',            views.ls_portal,             name='ls_portal'),
    path('billing/cancel/',            views.ls_cancel,             name='ls_cancel'),
    path('billing/pause/',             views.ls_pause,              name='ls_pause'),
    path('billing/change-plan/',       views.ls_change_plan,        name='ls_change_plan'),
    path('billing/cancel-downgrade/',  views.ls_cancel_downgrade,   name='ls_cancel_downgrade'),
    path('billing/apply-downgrade/',   views.ls_apply_downgrade,    name='ls_apply_downgrade'),
    path('billing/sync/',              views.ls_sync,               name='ls_sync'),
    path('billing/webhook/',           views.ls_webhook,            name='ls_webhook'),
    path('settings/invoices/export/', views.export_invoices_csv,  name='export_invoices_csv'),
    path('settings/invoices/<str:inv_id>/pdf/',      views.invoice_pdf,          name='invoice_pdf'),
    path('settings/invoices/<str:inv_id>/download/', views.invoice_pdf_download, name='invoice_pdf_download'),
    # Notifications
    path('notifications/prefs/',          views.save_notif_prefs_view,    name='save_notif_prefs'),
    path('notifications/channel/',        views.save_notif_channel_view,  name='save_notif_channel'),
    path('notifications/test/',           views.notif_test_view,          name='notif_test'),
    # CRM integrations (Settings → Integrations tab)
    path('integrations/zapier/save/',     views.crm_save_zapier_view,     name='crm_save_zapier'),
    path('integrations/test/',            views.crm_test_view,            name='crm_test'),
    path('integrations/disconnect/',      views.crm_disconnect_view,      name='crm_disconnect'),
    path('integrations/<str:provider>/start/',    views.crm_oauth_start,    name='crm_oauth_start'),
    path('integrations/<str:provider>/callback/', views.crm_oauth_callback, name='crm_oauth_callback'),
    path('notifications/<int:notif_id>/mark-opened/', views.mark_notif_opened_view, name='mark_notif_opened'),
    path('notifications/export/',         views.notifications_export_csv, name='notifications_export_csv'),
    # API portal
    path('api/', views.api_portal, name='api_portal'),
    path('api/keys/create/', views.api_key_create, name='api_key_create'),
    path('api/keys/revoke/', views.api_key_revoke, name='api_key_revoke'),
    # API v1
    path('api/v1/permits/', views.api_permits, name='api_permits'),
    path('api/v1/permits/ingest/', views.api_permits_ingest, name='api_permits_ingest'),
    path('api/v1/scrapers/run-cron/', views.api_run_scrapers_cron, name='api_run_scrapers_cron'),
    path('api/cron/recovery-emails/tick/', views.api_recovery_emails_tick, name='api_recovery_emails_tick'),
    path('api/v1/permits/<str:number>/', views.api_permit_detail, name='api_permit_detail'),
    path('api/v1/cities/', views.api_cities, name='api_cities'),
    path('api/v1/score/', views.api_score, name='api_score'),
    # Dev-only email preview (404s in production via DEBUG check)
    path('dev/email-preview/<str:template_name>/', views.email_preview, name='email_preview'),
]
