# Generated by Django 5.2.13 on 2026-06-09 21:39

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('content', models.TextField(default='')),
                ('cover_image_url', models.URLField(blank=True, default='')),
                ('meta_description', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('ai_generated', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=50, unique=True)),
                ('plan', models.CharField(max_length=50)),
                ('plan_label', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=20)),
                ('amount_cents', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=50)),
                ('period', models.CharField(blank=True, default='', max_length=100)),
                ('period_start', models.CharField(blank=True, default='', max_length=20)),
                ('period_end', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(default='paid', max_length=20)),
                ('payment', models.CharField(default='Whop', max_length=50)),
                ('billing_reason', models.CharField(blank=True, default='', max_length=50)),
                ('whop_membership_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=100)),
                ('plan_name', models.CharField(max_length=200)),
                ('plan_type', models.CharField(choices=[('residential', 'Residential'), ('datacenter', 'Datacenter'), ('ipv6', 'IPv6')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=core.models._default_expires_at)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('replied', 'Replied'), ('closed', 'Closed')], default='open', max_length=20)),
                ('reply_body', models.TextField(blank=True, default='')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(default='free', max_length=50)),
                ('bandwidth_used_gb', models.FloatField(default=0)),
                ('proxies_generated', models.IntegerField(default=0)),
                ('whop_membership_id', models.CharField(blank=True, default='', max_length=100)),
                ('whop_status', models.CharField(blank=True, default='', max_length=50)),
                ('whop_renews_at', models.CharField(blank=True, default='', max_length=50)),
                ('whop_cancelled', models.BooleanField(default=False)),
                ('whop_paused', models.BooleanField(default=False)),
                ('whop_mode', models.CharField(default='prod', max_length=10)),
                ('last_whop_sync_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_start', models.CharField(blank=True, default='', max_length=20)),
                ('billing_period_start', models.CharField(blank=True, default='', max_length=20)),
                ('billing_period_end', models.CharField(blank=True, default='', max_length=20)),
                ('payment_email_last_membership', models.CharField(blank=True, default='', max_length=100)),
                ('payment_email_last_plan', models.CharField(blank=True, default='', max_length=50)),
                ('proxy_api_key', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
